_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 55
                - 79
            "2":
                - 1
                - 55
                - 79
            "3":
                - 1
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.9.0
            "5": 0.18.0
            "8":
                - 1
                - 5
            "12": 0.18.0
            "13": linux-x86_64
dataset:
    value: Dataset500_Brain
learningRate:
    value: 0.01
model:
    value: nnUnet
optimizationSteps:
    value: 200
signature:
    value: 10k
